# Generated by Django 4.2.6 on 2023-12-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_authtoken'),
        ('helpsupport', '0003_rename_user_id_ticket_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='username',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
