# Generated by Django 4.2.6 on 2023-12-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_authtoken'),
        ('helpsupport', '0004_remove_ticket_username_ticket_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
