# Generated by Django 4.2.6 on 2023-11-15 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, null=True)),
                ('userimg', models.ImageField(upload_to='')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('best_hours', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='M', max_length=1)),
                ('worksstarttime', models.TimeField()),
                ('workendtime', models.TimeField()),
                ('selfstatement', models.CharField(choices=[('Warm', 'I generally feel warmer than other people in the room'), ('Same', 'In general, my experience is similar to others in terms of temperature'), ('Cold', 'I generally feel colder than other people in the room')], default='Same', max_length=4)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contribution', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
