# Generated by Django 4.2.6 on 2023-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
