# Generated by Django 4.2.6 on 2023-11-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
