# Generated by Django 4.2.6 on 2023-11-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='workendtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='worksstarttime',
            field=models.TimeField(null=True),
        ),
    ]
