# Generated by Django 4.2.6 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_account_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authtoken',
            field=models.TextField(null=True),
        ),
    ]
