# Generated by Django 4.2.6 on 2023-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authtoken',
            field=models.CharField(max_length=255),
        ),
    ]
