# Generated by Django 4.2.6 on 2024-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('group_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(related_name='user_groups', to='accounts.account')),
            ],
        ),
    ]
