# Generated by Django 4.2.6 on 2024-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_usergroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
