# Generated by Django 4.2.6 on 2024-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_surveygroups_delete_usergroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveygroups',
            name='end_date',
            field=models.DateField(default='2023-12-08'),
        ),
        migrations.AddField(
            model_name='surveygroups',
            name='start_date',
            field=models.DateField(default='2023-12-08'),
        ),
        migrations.AddField(
            model_name='surveygroups',
            name='trigger_times',
            field=models.JSONField(null=True),
        ),
    ]
