# Generated by Django 4.2.6 on 2024-04-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_alter_completedsurvey_user_id'),
        ('accounts', '0021_surveygroups_end_date_surveygroups_start_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyGroups',
            new_name='SurveyGroup',
        ),
    ]
