# Generated by Django 4.2.6 on 2024-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_surveygroups_surveygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authtoken',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
