# Generated by Django 4.2.6 on 2023-11-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_index', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=30)),
                ('survey_intro', models.CharField(max_length=100)),
                ('survey_points', models.PositiveSmallIntegerField()),
                ('survey_type', models.CharField(choices=[('PC', 'Personal Comfort'), ('AQ', 'Indoor Air Quality'), ('EQ', 'Indoor Environmental Quality')], default='PC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=150)),
                ('instruction', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Questions'), ('OPN', 'Open Ended'), ('SEL', 'Single Selection'), ('MSL', 'Multiple Selections'), ('SLD', 'Single Slide Bar'), ('MSD', 'Multiple Slide Bars')], default='MCQ', max_length=3)),
                ('survey_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSurvey',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('survey_active', models.BooleanField(default=False)),
                ('question_n_answer', models.JSONField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.JSONField()),
                ('next_question_id', models.PositiveSmallIntegerField(unique=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.question')),
            ],
        ),
    ]
