# Generated by Django 4.2.6 on 2023-11-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_user_id_completedsurvey_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_index',
            new_name='survey_id',
        ),
    ]
