# Generated by Django 4.2.6 on 2023-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_rename_survey_index_survey_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_question_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
