# Generated by Django 4.2.6 on 2023-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_answer_answers_alter_answer_next_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_question_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
