# Generated by Django 4.2.6 on 2023-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_survey_survey_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_points',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_intro',
            field=models.CharField(max_length=100),
        ),
    ]
