# Generated by Django 4.2.6 on 2023-11-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_authtoken'),
        ('surveys', '0008_survey_survey_points_alter_survey_survey_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsurvey',
            name='survey_name',
        ),
        migrations.RemoveField(
            model_name='completedsurvey',
            name='username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey_index',
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='survey_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='completedsurvey',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.survey'),
        ),
    ]
