# Generated by Django 4.2.6 on 2023-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_completedsurvey_survey_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsurvey',
            name='survey_active',
        ),
        migrations.AlterField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.survey'),
        ),
    ]
