# Generated by Django 4.2.6 on 2023-11-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_completedsurvey_survey_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='question',
            name='survey_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='surveys.survey'),
        ),
    ]
