# Generated by Django 4.2.6 on 2024-05-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_alter_completedsurvey_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_intro',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(max_length=200),
        ),
    ]
