# Generated by Django 4.2.6 on 2024-05-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_remove_answer_next_question_id_answer_unfoldings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='isinfirstqset',
            new_name='in_first_q_set',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='unfoldingsurvey',
            new_name='unfolding_survey',
        ),
    ]
