# Generated by Django 4.2.6 on 2024-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_rename_isinfirstqset_question_in_first_q_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_time',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
