# Generated by Django 4.2.6 on 2023-11-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedNotification',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=300)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('trigger_times', models.JSONField()),
                ('active', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
        ),
    ]
