# Generated by Django 4.2.6 on 2023-11-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_authtoken'),
        ('notifications', '0004_remove_issuednotification_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuednotification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='issuednotification',
            name='topic',
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='notification_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issuednotification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
