# Generated by Django 4.2.6 on 2023-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_issuednotification_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuednotification',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
