# Generated by Django 4.2.6 on 2023-12-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_authtoken'),
        ('notifications', '0006_alter_issuednotification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuednotification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
