# Generated by Django 4.2.6 on 2023-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_issuednotification_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuednotification',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='issuednotification',
            name='start_time',
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='start_date',
            field=models.DateField(),
        ),
    ]
