# Generated by Django 4.2.6 on 2023-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_issuednotification_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuednotification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='issuednotification',
            name='start_date',
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='end_time',
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='start_time',
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
    ]
