# Generated by Django 4.2.6 on 2023-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_issuednotification_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuednotification',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='issuednotification',
            name='start_time',
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='end_date',
            field=models.DateField(default='2023-12-08'),
        ),
        migrations.AddField(
            model_name='issuednotification',
            name='start_date',
            field=models.DateField(default='2023-12-08'),
        ),
    ]
